version: '3.4'

services:
  counter-manager-web:
    image: ${DOCKER_REGISTRY-}counter-manager-web
    container_name: counter-manager-web
    ports:
      - 8083:8083
      - 443:443
    build:
      context: .
      dockerfile: CounterManagerWeb/Dockerfile
    depends_on:
      - counter-manager-api

  counter-manager-api:
    image: ${DOCKER_REGISTRY-}counter-manager-api
    container_name: counter-manager-api
    ports:
      - 8082:8082
    build:
      context: .
      dockerfile: CounterManagerApi/Dockerfile
    depends_on:
      - counter-manager-db


  counter-manager-db:
    image: ${DOCKER_REGISTRY-}counter-manager-db
    container_name: counter-manager-db
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: CounterManagerDb/Dockerfile

  database:
    image: ${DOCKER_REGISTRY-}database
    container_name: database
    ports:
      - 3306:3306
    build:
      context: ./DbScripts
      dockerfile: Dockerfile
    env_file:
      - DbScripts/env.list