#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mariadb:10.7.4

COPY ./init.sql /docker-entrypoint-initdb.d/ddl.sql